const products = [
  {
    id: "001",
    name: "Wireless Bluetooth Headphones",
    description:
      "Noise-cancelling over-the-ear headphones with high-quality sound.",
    price: 129.99,
    inventory: 120,
    sales: 80,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/100/200/300",
  },
  {
    id: "002",
    name: "Laptop Stand Adjustable",
    description: "Ergonomic stand for laptops up to 17 inches.",
    price: 39.99,
    inventory: 200,
    sales: 150,
    retailer: "Walmart",
    imageUrl: "https://picsum.photos/id/101/200/300",
  },
  {
    id: "003",
    name: "Smart LED TV 50-inch",
    description: "Ultra HD Smart TV with HDR and Alexa Compatibility.",
    price: 399.99,
    inventory: 100,
    sales: 85,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/102/200/300",
  },
  {
    id: "004",
    name: "Gaming Mouse RGB",
    description: "High precision laser mouse with customizable RGB lights.",
    price: 49.99,
    inventory: 250,
    sales: 180,
    retailer: "Walmart",
    imageUrl: "https://picsum.photos/id/103/200/300",
  },
  {
    id: "005",
    name: "Kitchen Blender 700W",
    description: "Multi-speed blender for smoothies, sauces, and more.",
    price: 59.99,
    inventory: 150,
    sales: 110,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/104/200/300",
  },
  {
    id: "006",
    name: "Portable Camping Tent",
    description: "Waterproof 4-person outdoor tent.",
    price: 109.99,
    inventory: 500,
    sales: 300,
    retailer: "Walmart",
    imageUrl: "https://picsum.photos/id/105/200/300",
  },
  {
    id: "007",
    name: "Men's Running Shoes",
    description: "Breathable athletic shoes for long-distance running.",
    price: 89.99,
    inventory: 400,
    sales: 320,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/106/200/300",
  },
  {
    id: "008",
    name: "Digital Camera 24MP",
    description: "Compact digital camera with optical zoom.",
    price: 199.99,
    inventory: 170,
    sales: 150,
    retailer: "Walmart",
    imageUrl: "https://picsum.photos/id/107/200/300",
  },
  {
    id: "009",
    name: "Yoga Mat Non-slip",
    description: "Eco-friendly, cushioned yoga mat.",
    price: 29.99,
    inventory: 300,
    sales: 250,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/108/200/300",
  },
  {
    id: "010",
    name: "Electric Toothbrush",
    description: "Rechargeable toothbrush with multiple brushing modes.",
    price: 79.99,
    inventory: 210,
    sales: 185,
    retailer: "Walmart",
    imageUrl: "https://picsum.photos/id/109/200/300",
  },
  {
    id: "011",
    name: "Gardening Tool Set",
    description: "Essential tools for gardening enthusiasts.",
    price: 34.99,
    inventory: 220,
    sales: 200,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/110/200/300",
  },
  {
    id: "012",
    name: "Electric Kettle 1.5L",
    description: "Quick boiling kettle with auto-shut feature.",
    price: 44.99,
    inventory: 180,
    sales: 160,
    retailer: "Walmart",
    imageUrl: "https://picsum.photos/id/111/200/300",
  },
  {
    id: "013",
    name: "Wireless Phone Charger",
    description: "Fast charging wireless pad for smartphones.",
    price: 24.99,
    inventory: 310,
    sales: 280,
    retailer: "Amazon",
    imageUrl: "https://picsum.photos/id/112/200/300",
  },
];
